### Create
POST http://uzcarduz.herokuapp.com/api/v1/card
Authorization: Basic bank bankjon

### Update Status
PUT http://uzcarduz.herokuapp.com/api/v1/card/status
Authorization: Basic bank bankjon
Content-Type: application/json

{
  "cardNumber": "8600324432080802",
  "status": "ACTIVE"
}

### Assign Phone
PUT http://uzcarduz.herokuapp.com/api/v1/card/phone/8a8a839980ff25200180ff25536a0000
Authorization: Basic bank bankjon
Content-Type: application/json

{
  "cardNumber": "8600324432080802"
}

### List
GET http://uzcarduz.herokuapp.com/api/v1/card/list/+998991234567
Authorization: Basic admin adminjon

### Card Balance
GET http://uzcarduz.herokuapp.com/api/v1/card/balance
Authorization: Basic admin adminjon
Content-Type: application/json

{
  "cardNumber": "8600814069764408"
}

### List By Client
GET http://uzcarduz.herokuapp.com/api/v1/card/client/8a8a839980ffbd9d0180ffbe4b300000
Authorization: Basic admin adminjon

### Get By Card Number
GET http://uzcarduz.herokuapp.com/api/v1/card
Authorization: Basic profile profilejon
Content-Type: application/json

{
  "cardNumber": "8600481585940784"
}

### List By Filter
GET http://uzcarduz.herokuapp.com/api/v1/card/filter
Authorization: Basic admin adminjon
Content-Type: application/json

{
  "name": "ALi",
  "fromBalance": 800,
  "toBalance": 10000,
  "expDate": "2027-05-26",
  "createdDate": "2022-05-26T15:36:14.611000"
}

