### Create
POST http://uzcarduz.herokuapp.com/api/v1/client
Authorization: Basic bank bankjon
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev",
  "phone": "+998991234567"
}

### Update Bio
PUT http://uzcarduz.herokuapp.com/api/v1/client/bio/8a8a839980ffbd9d0180ffbe4b300000
Authorization: Basic bank bankjon
Content-Type: application/json

{
  "name": "Ali",
  "surname": "Aliyev"
}

### Update Phone
PUT http://uzcarduz.herokuapp.com/api/v1/client/phone/8a8a839980ff25200180ff25536a0000
Authorization: Basic bank bankjon
Content-Type: application/json

{
  "phone": "+998991234568"
}

### Update Status
PUT http://uzcarduz.herokuapp.com/api/v1/client/status/8a8a839980ff25200180ff25536a0000
Authorization: Basic bank bankjon
Content-Type: application/json

{
  "status": "BLOCK"
}

### List
GET http://uzcarduz.herokuapp.com/api/v1/client/list?page=0&size=0
Authorization: Basic admin adminjon

### List By Profile
GET http://uzcarduz.herokuapp.com/api/v1/client/list/bank
Authorization: Basic profile profilejon

### Get By Client
GET http://uzcarduz.herokuapp.com/api/v1/client/8a8a839980ff25200180ff25536a0000
Authorization: Basic profile profilejon
